variable "cidr" {}
variable "name" {}
variable "environment" {}
variable "tags" {}
variable "enable_dns_support" {}
variable "enable_dns_hostnames" {}
variable "Public_sn_cidr" {}
variable "Private_sn_cidr_1" {}
variable "public_subnet_az" {}
variable "public_rt_cidr" {}
variable "Private_rt_cidr" {}
#variable "create-eip" {}